# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


同樣是分配一塊記憶體空間，但 np.zero 需要把值設成零，而 np.empty 不需要特別把值設成零，所以在處理速度上， np.empty 更快

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [4]:
# 參考解答
a = np.random.rand(2, 3)*100
print(a)

a = np.floor(a)
print(a)

[[ 4.44620636 53.32980472 31.95318726]
 [59.39133701 53.07240316 33.76794222]]
[[ 4. 53. 31.]
 [59. 53. 33.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [5]:
m = 20
n = 40

a = m + np.random.rand(2, 3)*(n-m)
print(a)

a = np.floor(a)
print(a)

[[35.92658013 23.23998053 22.88657023]
 [36.36426533 23.80718833 20.51048281]]
[[35. 23. 22.]
 [36. 23. 20.]]
