# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np

a = np.arange(10)
b = np.arange(10).reshape(2, 5)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [2]:
print('list(a): ', list(a))
print('tolist(a): ', a.tolist())
print()

print('list(b): ', list(b))
print('tolist(b): ', b.tolist())

list(a):  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
tolist(a):  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

list(b):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
tolist(b):  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [3]:
# 記得先 Import 正確的套件

In [4]:
a = np.random.randint(10, size=6) 

print(a)
print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('length: ', len(a))
print('type: ', type(a))

[5 6 2 4 6 0]
ndim:  1
shape:  (6,)
size:  6
dtype:  int32
itemsize:  4
length:  6
type:  <class 'numpy.ndarray'>


In [5]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('length: ', len(b))
print('type: ', type(b))

[[2 5 0 8]
 [3 8 3 7]
 [5 3 8 7]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int32
itemsize:  4
length:  3
type:  <class 'numpy.ndarray'>


In [6]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('length: ', len(c))
print('type: ', type(c))

[[[8 1]
  [1 4]
  [9 8]]

 [[1 8]
  [1 9]
  [9 9]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int32
itemsize:  4
length:  2
type:  <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [7]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[8, 9, 9, 0, 0, 7]
[8, 9, 9, 0, 0, 7]


In [8]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[3, 4, 6, 6], [0, 6, 4, 2], [3, 6, 9, 4]]
[array([3, 4, 6, 6]), array([0, 6, 4, 2]), array([3, 6, 9, 4])]


In [9]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[4, 6], [3, 6], [5, 9]], [[5, 7], [7, 0], [2, 0]]]
[array([[4, 6],
       [3, 6],
       [5, 9]]), array([[5, 7],
       [7, 0],
       [2, 0]])]


In [12]:
def tolist(iterable):
    
    # if iterable.shape[0] == 1:                   # 最後一層，回傳 list() 轉換
    #    return list(iterable) 
    
    if type(iterable) != np.ndarray:               # 或是拆解到最後一層的元素，直接回傳
        return iterable
    
    #new = []                         # 非最後一層，則對該層的所有 array 元素遞迴呼叫 tolist() 直到最後一層 
    #for arr in iterable:
        #new.append(tolist(arr))
    
    #return new
        
    return [tolist(arr) for arr in iterable]

In [13]:
print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 9, 9, 0, 0, 7]
[[3, 4, 6, 6], [0, 6, 4, 2], [3, 6, 9, 4]]
[[[4, 6], [3, 6], [5, 9]], [[5, 7], [7, 0], [2, 0]]]
