# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [2]:
# 記得先 Import 正確的套件
import numpy as np

a = np.arange(11)
a[(a>=3) & (a<7)] *= -1

print(a)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [8]:
A = np.random.rand(3, 6)
print(A)
print(A[A>0.5].size)

[[0.95590633 0.27066279 0.07911693 0.22253744 0.32508111 0.89352256]
 [0.7962694  0.41465306 0.314059   0.54894809 0.98538703 0.837104  ]
 [0.75431149 0.77965337 0.56246456 0.58854517 0.7202111  0.81699754]]
12
